= Release Process

This guide provides a chronological steps which goes through release tagging, staging, verification and publishing.

== Prerequisites

You need to make sure you have access to the JBoss nexus server, with permissions to stage, and release.  The documents above have information on this, but if you are not sure please contact JBoss helpdesk, and follow up with the project lead.

=== Release settings

Before beginning any of the procedures below you need to setup your maven installation.

Use following template for a `release-settings.xml` and pass it to all Maven executions (just change `username`, `password` and `localRepository` settings as convenient):

[source,xml]
----
<settings>
    <localRepository>/tmp/richfaces-release-localRepository</localRepository>

    <mirrors>
        <mirror> 
            <id>jboss-staging-repository-group</id> 
            <mirrorOf>*,!jboss-qa-releases-repository</mirrorOf> 
            <name>JBoss.org Staging Repository Group</name> 
            <url>https://repository.jboss.org/nexus/content/groups/staging</url> 
        </mirror>
    </mirrors>

    <servers>
        <server>
            <id>jboss-releases-repository</id>
            <username>{your_email}</username>
            <password>{your_password}</password>
        </server>
    </servers>

</settings>
----

Using these settings you will use separated local repository which will be popullated only with artifacts from JBoss Staging repository and released artifacts. That way you can verify that the build is reproducible using JBoss Maven repositories.

=== Environment

|===
| Maven | 3.0.4

| JDK | Oracle JDK 1.7

| MAVEN_OPTS | -Xmx1024m -XX:MaxPermSize=512m
|===

=== Notify Development Team

Also the person performing any of the releases below should also post a message to the RichFaces developer forum stating:

____
The release process for <4.5.0.Alpha1> is about to begin. Further commits into develop branch will not be considered in release.
____

When the release is completed be sure to post to the forums again.

=== Review Issue Tracker Status and Continuous Integration

Before starting any release steps, make sure the CI tests pass and that all issues scheduled to particular version are resolved.

=== Finish Release Notes

`dist/release-notes.txt` should be updated before starting with release (you can use the raw output of JIRA's Release Notes for particular version.


== Tagging Core Framework Modules

=== Procedure

Checkout project modules

----
$ git clone git@github.com:richfaces4/components.git
$ git clone git@github.com:richfaces4/showcase.git
----

*All following steps needs to be performed for both modules: `{components,showcase}`*.

Diverge a release branch - the development can proceed on the `master` branch when no parallel development is expected (in that case, we can use the `4.5.x` as a release branch):

----
cd {components,showcase}/
git checkout <4.5.x> -b <release/4.5.0.Alpha1>
----

Bump to release versions:
 
----
$ bash change_version.sh -r -o <4.5.0-SNAPSHOT> -n <4.5.0.Alpha1>
$ git add -A
$ git commit -m 'changing version to <4.5.0.Alpha1>'
----
 
In next steps, be sure to point maven to local copy of release `settings.xml` and to activate profiles build and release in each step

Run dry run to verify build with release versions

----
$ mvn -s <settings.xml> -P release clean verify
----

If there are problems with build ( failed tests, SNAPSHOT dependencies, etc...) communicate with development team, and resolve.

Tag the release commit (but do not push the tag):

----
$ git tag -a <4.5.0.Alpha1> -m "Tagging release <4.5.0.Alpha1>"
----

Publish Release Branch to repository

----
$ git push origin <release/4.5.0.Alpha1>
----

== Release Staging

Now you can perform the actual release build from the tag, and deploy using
(you can use install instead of deploy in case you want just build release locally)

----
$ mvn -s <settings.xml> -P release clean deploy
----
 
This will build from the tag, and perform the actual uploads to the JBoss staging repo.

If there is authentication problems contact project lead

If there are errors uploading for some reason you need to "drop" what ever was staged following: Maven Deploying a Release

Then attempt the build again.  If the problems continue contact project lead
Next you need to "close" the stage following the Maven Deploying a Release with the comment "RichFaces <4.5.0.Alpha1> Stage"
 
The release is now staged, and the release jira should be updated with links to the public stage, and the private stage URL.

== Releasing/Dropping

Once QE and development have verified and cleared the staged release following the release testing process, next step is to promote the staged bits to JBoss maven release repo.
 
This is very easy.  Simply log into the nexus server following https://community.jboss.org/docs/DOC-15179[Maven Deploying a Release] and "promote" the release.
 
If QE and development find issues, and the release needs to be dropped follow the directions above, and "drop" the stage.


=== Push Tag

Once the release verification is successfully performed, you can also push the tag to the repository:

----
$ git push origin <4.5.0.Alpha1>
----

=== Merging Release branch with Master branch

One more step is required to finish the release process - publish release branches on GitHub.
It is recommended to do following process for each framework repository separately since there may occur merge conflicts.
 
update the develop and master branches (in order to merge to latest state)

----
$ git fetch origin
$ git checkout <4.5.x>
$ git rebase <origin/4.5.x>
----

merge release branch

----
$ git checkout <4.5.x>
$ git merge --no-ff <release/4.5.0.Alpha1>
# resolve merge conflicts
$ git branch -d <release/4.5.0.Alpha1>
----

bump versions on release branch to new development version

----
$ bash change_version.sh -r -o <4.5.0.Alpha1> -n <4.5.0-SNAPSHOT>
$ git add -A
$ git commit -m 'changing versions back to development: <4.5.0-SNAPSHOT>'
----

try the snapshot build

----
$ mvn clean verify
----

publish merged branches
warning: be sure to do not push changes in master when this is not Final release! (see note in step (2))

----
$ git push origin <4.5.x>:<4.5.x>
----

remove the remote release branch

----
$ git push origin :<release/4.5.0.Alpha1>
----
